"""Add returned and returned_at to Book

Revision ID: ef985ff2cb81
Revises: 8b9b76679427
Create Date: 2025-04-10 13:52:26.435931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef985ff2cb81'
down_revision = '8b9b76679427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('returned_at')
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
